export interface CountryData {
  code: string;
  name: string;
  flag: string;
  dialCode: string;
  currency: string;
  symbol: string;
}

export const POPULAR_COUNTRIES: CountryData[] = [
  { code: "IN", name: "India", flag: "🇮🇳", dialCode: "+91", currency: "INR", symbol: "₹" },
  { code: "US", name: "United States", flag: "🇺🇸", dialCode: "+1", currency: "USD", symbol: "$" },
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪", dialCode: "+971", currency: "AED", symbol: "AED" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧", dialCode: "+44", currency: "GBP", symbol: "£" },
  { code: "KE", name: "Kenya", flag: "🇰🇪", dialCode: "+254", currency: "KES", symbol: "KSh" },
];

export const ALL_COUNTRIES: CountryData[] = [
  ...POPULAR_COUNTRIES,
  { code: "AF", name: "Afghanistan", flag: "🇦🇫", dialCode: "+93", currency: "AFN", symbol: "؋" },
  { code: "AL", name: "Albania", flag: "🇦🇱", dialCode: "+355", currency: "ALL", symbol: "L" },
  { code: "DZ", name: "Algeria", flag: "🇩🇿", dialCode: "+213", currency: "DZD", symbol: "د.ج" },
  { code: "AD", name: "Andorra", flag: "🇦🇩", dialCode: "+376", currency: "EUR", symbol: "€" },
  { code: "AO", name: "Angola", flag: "🇦🇴", dialCode: "+244", currency: "AOA", symbol: "Kz" },
  { code: "AG", name: "Antigua and Barbuda", flag: "🇦🇬", dialCode: "+1-268", currency: "XCD", symbol: "$" },
  { code: "AR", name: "Argentina", flag: "🇦🇷", dialCode: "+54", currency: "ARS", symbol: "$" },
  { code: "AM", name: "Armenia", flag: "🇦🇲", dialCode: "+374", currency: "AMD", symbol: "֏" },
  { code: "AU", name: "Australia", flag: "🇦🇺", dialCode: "+61", currency: "AUD", symbol: "$" },
  { code: "AT", name: "Austria", flag: "🇦🇹", dialCode: "+43", currency: "EUR", symbol: "€" },
  { code: "AZ", name: "Azerbaijan", flag: "🇦🇿", dialCode: "+994", currency: "AZN", symbol: "₼" },
  { code: "BS", name: "Bahamas", flag: "🇧🇸", dialCode: "+1-242", currency: "BSD", symbol: "$" },
  { code: "BH", name: "Bahrain", flag: "🇧🇭", dialCode: "+973", currency: "BHD", symbol: ".د.ب" },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩", dialCode: "+880", currency: "BDT", symbol: "৳" },
  { code: "BB", name: "Barbados", flag: "🇧🇧", dialCode: "+1-246", currency: "BBD", symbol: "$" },
  { code: "BY", name: "Belarus", flag: "🇧🇾", dialCode: "+375", currency: "BYN", symbol: "Br" },
  { code: "BE", name: "Belgium", flag: "🇧🇪", dialCode: "+32", currency: "EUR", symbol: "€" },
  { code: "BZ", name: "Belize", flag: "🇧🇿", dialCode: "+501", currency: "BZD", symbol: "$" },
  { code: "BJ", name: "Benin", flag: "🇧🇯", dialCode: "+229", currency: "XOF", symbol: "Fr" },
  { code: "BT", name: "Bhutan", flag: "🇧🇹", dialCode: "+975", currency: "BTN", symbol: "Nu." },
  { code: "BO", name: "Bolivia", flag: "🇧🇴", dialCode: "+591", currency: "BOB", symbol: "Bs." },
  { code: "BA", name: "Bosnia and Herzegovina", flag: "🇧🇦", dialCode: "+387", currency: "BAM", symbol: "KM" },
  { code: "BW", name: "Botswana", flag: "🇧🇼", dialCode: "+267", currency: "BWP", symbol: "P" },
  { code: "BR", name: "Brazil", flag: "🇧🇷", dialCode: "+55", currency: "BRL", symbol: "R$" },
  { code: "BN", name: "Brunei", flag: "🇧🇳", dialCode: "+673", currency: "BND", symbol: "$" },
  { code: "BG", name: "Bulgaria", flag: "🇧🇬", dialCode: "+359", currency: "BGN", symbol: "лв" },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫", dialCode: "+226", currency: "XOF", symbol: "Fr" },
  { code: "BI", name: "Burundi", flag: "🇧🇮", dialCode: "+257", currency: "BIF", symbol: "Fr" },
  { code: "KH", name: "Cambodia", flag: "🇰🇭", dialCode: "+855", currency: "KHR", symbol: "៛" },
  { code: "CM", name: "Cameroon", flag: "🇨🇲", dialCode: "+237", currency: "XAF", symbol: "Fr" },
  { code: "CA", name: "Canada", flag: "🇨🇦", dialCode: "+1", currency: "CAD", symbol: "$" },
  { code: "CV", name: "Cape Verde", flag: "🇨🇻", dialCode: "+238", currency: "CVE", symbol: "Esc" },
  { code: "CF", name: "Central African Republic", flag: "🇨🇫", dialCode: "+236", currency: "XAF", symbol: "Fr" },
  { code: "TD", name: "Chad", flag: "🇹🇩", dialCode: "+235", currency: "XAF", symbol: "Fr" },
  { code: "CL", name: "Chile", flag: "🇨🇱", dialCode: "+56", currency: "CLP", symbol: "$" },
  { code: "CN", name: "China", flag: "🇨🇳", dialCode: "+86", currency: "CNY", symbol: "¥" },
  { code: "CO", name: "Colombia", flag: "🇨🇴", dialCode: "+57", currency: "COP", symbol: "$" },
  { code: "KM", name: "Comoros", flag: "🇰🇲", dialCode: "+269", currency: "KMF", symbol: "Fr" },
  { code: "CG", name: "Congo (Brazzaville)", flag: "🇨🇬", dialCode: "+242", currency: "XAF", symbol: "Fr" },
  { code: "CD", name: "Congo (Kinshasa)", flag: "🇨🇩", dialCode: "+243", currency: "CDF", symbol: "Fr" },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷", dialCode: "+506", currency: "CRC", symbol: "₡" },
  { code: "CI", name: "Ivory Coast", flag: "🇨🇮", dialCode: "+225", currency: "XOF", symbol: "Fr" },
  { code: "HR", name: "Croatia", flag: "🇭🇷", dialCode: "+385", currency: "EUR", symbol: "€" },
  { code: "CU", name: "Cuba", flag: "🇨🇺", dialCode: "+53", currency: "CUP", symbol: "$" },
  { code: "CY", name: "Cyprus", flag: "🇨🇾", dialCode: "+357", currency: "EUR", symbol: "€" },
  { code: "CZ", name: "Czech Republic", flag: "🇨🇿", dialCode: "+420", currency: "CZK", symbol: "Kč" },
  { code: "DK", name: "Denmark", flag: "🇩🇰", dialCode: "+45", currency: "DKK", symbol: "kr" },
  { code: "DJ", name: "Djibouti", flag: "🇩🇯", dialCode: "+253", currency: "DJF", symbol: "Fr" },
  { code: "DM", name: "Dominica", flag: "🇩🇲", dialCode: "+1-767", currency: "XCD", symbol: "$" },
  { code: "DO", name: "Dominican Republic", flag: "🇩🇴", dialCode: "+1-809", currency: "DOP", symbol: "$" },
  { code: "EC", name: "Ecuador", flag: "🇪🇨", dialCode: "+593", currency: "USD", symbol: "$" },
  { code: "EG", name: "Egypt", flag: "🇪🇬", dialCode: "+20", currency: "EGP", symbol: "£" },
  { code: "SV", name: "El Salvador", flag: "🇸🇻", dialCode: "+503", currency: "USD", symbol: "$" },
  { code: "GQ", name: "Equatorial Guinea", flag: "🇬🇶", dialCode: "+240", currency: "XAF", symbol: "Fr" },
  { code: "ER", name: "Eritrea", flag: "🇪🇷", dialCode: "+291", currency: "ERN", symbol: "Nfk" },
  { code: "EE", name: "Estonia", flag: "🇪🇪", dialCode: "+372", currency: "EUR", symbol: "€" },
  { code: "ET", name: "Ethiopia", flag: "🇪🇹", dialCode: "+251", currency: "ETB", symbol: "Br" },
  { code: "FJ", name: "Fiji", flag: "🇫🇯", dialCode: "+679", currency: "FJD", symbol: "$" },
  { code: "FI", name: "Finland", flag: "🇫🇮", dialCode: "+358", currency: "EUR", symbol: "€" },
  { code: "FR", name: "France", flag: "🇫🇷", dialCode: "+33", currency: "EUR", symbol: "€" },
  { code: "GA", name: "Gabon", flag: "🇬🇦", dialCode: "+241", currency: "XAF", symbol: "Fr" },
  { code: "GM", name: "Gambia", flag: "🇬🇲", dialCode: "+220", currency: "GMD", symbol: "D" },
  { code: "GE", name: "Georgia", flag: "🇬🇪", dialCode: "+995", currency: "GEL", symbol: "₾" },
  { code: "DE", name: "Germany", flag: "🇩🇪", dialCode: "+49", currency: "EUR", symbol: "€" },
  { code: "GH", name: "Ghana", flag: "🇬🇭", dialCode: "+233", currency: "GHS", symbol: "₵" },
  { code: "GR", name: "Greece", flag: "🇬🇷", dialCode: "+30", currency: "EUR", symbol: "€" },
  { code: "GD", name: "Grenada", flag: "🇬🇩", dialCode: "+1-473", currency: "XCD", symbol: "$" },
  { code: "GT", name: "Guatemala", flag: "🇬🇹", dialCode: "+502", currency: "GTQ", symbol: "Q" },
  { code: "GN", name: "Guinea", flag: "🇬🇳", dialCode: "+224", currency: "GNF", symbol: "Fr" },
  { code: "GW", name: "Guinea-Bissau", flag: "🇬🇼", dialCode: "+245", currency: "XOF", symbol: "Fr" },
  { code: "GY", name: "Guyana", flag: "🇬🇾", dialCode: "+592", currency: "GYD", symbol: "$" },
  { code: "HT", name: "Haiti", flag: "🇭🇹", dialCode: "+509", currency: "HTG", symbol: "G" },
  { code: "HN", name: "Honduras", flag: "🇭🇳", dialCode: "+504", currency: "HNL", symbol: "L" },
  { code: "HK", name: "Hong Kong", flag: "🇭🇰", dialCode: "+852", currency: "HKD", symbol: "$" },
  { code: "HU", name: "Hungary", flag: "🇭🇺", dialCode: "+36", currency: "HUF", symbol: "Ft" },
  { code: "IS", name: "Iceland", flag: "🇮🇸", dialCode: "+354", currency: "ISK", symbol: "kr" },
  { code: "ID", name: "Indonesia", flag: "🇮🇩", dialCode: "+62", currency: "IDR", symbol: "Rp" },
  { code: "IR", name: "Iran", flag: "🇮🇷", dialCode: "+98", currency: "IRR", symbol: "﷼" },
  { code: "IQ", name: "Iraq", flag: "🇮🇶", dialCode: "+964", currency: "IQD", symbol: "ع.د" },
  { code: "IE", name: "Ireland", flag: "🇮🇪", dialCode: "+353", currency: "EUR", symbol: "€" },
  { code: "IL", name: "Israel", flag: "🇮🇱", dialCode: "+972", currency: "ILS", symbol: "₪" },
  { code: "IT", name: "Italy", flag: "🇮🇹", dialCode: "+39", currency: "EUR", symbol: "€" },
  { code: "JM", name: "Jamaica", flag: "🇯🇲", dialCode: "+1-876", currency: "JMD", symbol: "$" },
  { code: "JP", name: "Japan", flag: "🇯🇵", dialCode: "+81", currency: "JPY", symbol: "¥" },
  { code: "JO", name: "Jordan", flag: "🇯🇴", dialCode: "+962", currency: "JOD", symbol: "د.ا" },
  { code: "KZ", name: "Kazakhstan", flag: "🇰🇿", dialCode: "+7", currency: "KZT", symbol: "₸" },
  { code: "KI", name: "Kiribati", flag: "🇰🇮", dialCode: "+686", currency: "AUD", symbol: "$" },
  { code: "KP", name: "North Korea", flag: "🇰🇵", dialCode: "+850", currency: "KPW", symbol: "₩" },
  { code: "KR", name: "South Korea", flag: "🇰🇷", dialCode: "+82", currency: "KRW", symbol: "₩" },
  { code: "KW", name: "Kuwait", flag: "🇰🇼", dialCode: "+965", currency: "KWD", symbol: "د.ك" },
  { code: "KG", name: "Kyrgyzstan", flag: "🇰🇬", dialCode: "+996", currency: "KGS", symbol: "с" },
  { code: "LA", name: "Laos", flag: "🇱🇦", dialCode: "+856", currency: "LAK", symbol: "₭" },
  { code: "LV", name: "Latvia", flag: "🇱🇻", dialCode: "+371", currency: "EUR", symbol: "€" },
  { code: "LB", name: "Lebanon", flag: "🇱🇧", dialCode: "+961", currency: "LBP", symbol: "ل.ل" },
  { code: "LS", name: "Lesotho", flag: "🇱🇸", dialCode: "+266", currency: "LSL", symbol: "L" },
  { code: "LR", name: "Liberia", flag: "🇱🇷", dialCode: "+231", currency: "LRD", symbol: "$" },
  { code: "LY", name: "Libya", flag: "🇱🇾", dialCode: "+218", currency: "LYD", symbol: "ل.د" },
  { code: "LI", name: "Liechtenstein", flag: "🇱🇮", dialCode: "+423", currency: "CHF", symbol: "Fr." },
  { code: "LT", name: "Lithuania", flag: "🇱🇹", dialCode: "+370", currency: "EUR", symbol: "€" },
  { code: "LU", name: "Luxembourg", flag: "🇱🇺", dialCode: "+352", currency: "EUR", symbol: "€" },
  { code: "MO", name: "Macau", flag: "🇲🇴", dialCode: "+853", currency: "MOP", symbol: "P" },
  { code: "MK", name: "North Macedonia", flag: "🇲🇰", dialCode: "+389", currency: "MKD", symbol: "ден" },
  { code: "MG", name: "Madagascar", flag: "🇲🇬", dialCode: "+261", currency: "MGA", symbol: "Ar" },
  { code: "MW", name: "Malawi", flag: "🇲🇼", dialCode: "+265", currency: "MWK", symbol: "MK" },
  { code: "MY", name: "Malaysia", flag: "🇲🇾", dialCode: "+60", currency: "MYR", symbol: "RM" },
  { code: "MV", name: "Maldives", flag: "🇲🇻", dialCode: "+960", currency: "MVR", symbol: ".ރ" },
  { code: "ML", name: "Mali", flag: "🇲🇱", dialCode: "+223", currency: "XOF", symbol: "Fr" },
  { code: "MT", name: "Malta", flag: "🇲🇹", dialCode: "+356", currency: "EUR", symbol: "€" },
  { code: "MH", name: "Marshall Islands", flag: "🇲🇭", dialCode: "+692", currency: "USD", symbol: "$" },
  { code: "MR", name: "Mauritania", flag: "🇲🇷", dialCode: "+222", currency: "MRU", symbol: "UM" },
  { code: "MU", name: "Mauritius", flag: "🇲🇺", dialCode: "+230", currency: "MUR", symbol: "₨" },
  { code: "MX", name: "Mexico", flag: "🇲🇽", dialCode: "+52", currency: "MXN", symbol: "$" },
  { code: "FM", name: "Micronesia", flag: "🇫🇲", dialCode: "+691", currency: "USD", symbol: "$" },
  { code: "MD", name: "Moldova", flag: "🇲🇩", dialCode: "+373", currency: "MDL", symbol: "L" },
  { code: "MC", name: "Monaco", flag: "🇲🇨", dialCode: "+377", currency: "EUR", symbol: "€" },
  { code: "MN", name: "Mongolia", flag: "🇲🇳", dialCode: "+976", currency: "MNT", symbol: "₮" },
  { code: "ME", name: "Montenegro", flag: "🇲🇪", dialCode: "+382", currency: "EUR", symbol: "€" },
  { code: "MA", name: "Morocco", flag: "🇲🇦", dialCode: "+212", currency: "MAD", symbol: "د.م." },
  { code: "MZ", name: "Mozambique", flag: "🇲🇿", dialCode: "+258", currency: "MZN", symbol: "MT" },
  { code: "MM", name: "Myanmar", flag: "🇲🇲", dialCode: "+95", currency: "MMK", symbol: "Ks" },
  { code: "NA", name: "Namibia", flag: "🇳🇦", dialCode: "+264", currency: "NAD", symbol: "$" },
  { code: "NR", name: "Nauru", flag: "🇳🇷", dialCode: "+674", currency: "AUD", symbol: "$" },
  { code: "NP", name: "Nepal", flag: "🇳🇵", dialCode: "+977", currency: "NPR", symbol: "₨" },
  { code: "NL", name: "Netherlands", flag: "🇳🇱", dialCode: "+31", currency: "EUR", symbol: "€" },
  { code: "NZ", name: "New Zealand", flag: "🇳🇿", dialCode: "+64", currency: "NZD", symbol: "$" },
  { code: "NI", name: "Nicaragua", flag: "🇳🇮", dialCode: "+505", currency: "NIO", symbol: "C$" },
  { code: "NE", name: "Niger", flag: "🇳🇪", dialCode: "+227", currency: "XOF", symbol: "Fr" },
  { code: "NO", name: "Norway", flag: "🇳🇴", dialCode: "+47", currency: "NOK", symbol: "kr" },
  { code: "OM", name: "Oman", flag: "🇴🇲", dialCode: "+968", currency: "OMR", symbol: "ر.ع." },
  { code: "PK", name: "Pakistan", flag: "🇵🇰", dialCode: "+92", currency: "PKR", symbol: "₨" },
  { code: "PW", name: "Palau", flag: "🇵🇼", dialCode: "+680", currency: "USD", symbol: "$" },
  { code: "PA", name: "Panama", flag: "🇵🇦", dialCode: "+507", currency: "PAB", symbol: "B/." },
  { code: "PG", name: "Papua New Guinea", flag: "🇵🇬", dialCode: "+675", currency: "PGK", symbol: "K" },
  { code: "PY", name: "Paraguay", flag: "🇵🇾", dialCode: "+595", currency: "PYG", symbol: "₲" },
  { code: "PE", name: "Peru", flag: "🇵🇪", dialCode: "+51", currency: "PEN", symbol: "S/." },
  { code: "PH", name: "Philippines", flag: "🇵🇭", dialCode: "+63", currency: "PHP", symbol: "₱" },
  { code: "PL", name: "Poland", flag: "🇵🇱", dialCode: "+48", currency: "PLN", symbol: "zł" },
  { code: "PT", name: "Portugal", flag: "🇵🇹", dialCode: "+351", currency: "EUR", symbol: "€" },
  { code: "QA", name: "Qatar", flag: "🇶🇦", dialCode: "+974", currency: "QAR", symbol: "ر.ق" },
  { code: "RO", name: "Romania", flag: "🇷🇴", dialCode: "+40", currency: "RON", symbol: "lei" },
  { code: "RU", name: "Russia", flag: "🇷🇺", dialCode: "+7", currency: "RUB", symbol: "₽" },
  { code: "RW", name: "Rwanda", flag: "🇷🇼", dialCode: "+250", currency: "RWF", symbol: "FRw" },
  { code: "KN", name: "Saint Kitts and Nevis", flag: "🇰🇳", dialCode: "+1-869", currency: "XCD", symbol: "$" },
  { code: "LC", name: "Saint Lucia", flag: "🇱🇨", dialCode: "+1-758", currency: "XCD", symbol: "$" },
  { code: "VC", name: "Saint Vincent", flag: "🇻🇨", dialCode: "+1-784", currency: "XCD", symbol: "$" },
  { code: "WS", name: "Samoa", flag: "🇼🇸", dialCode: "+685", currency: "WST", symbol: "T" },
  { code: "SM", name: "San Marino", flag: "🇸🇲", dialCode: "+378", currency: "EUR", symbol: "€" },
  { code: "ST", name: "Sao Tome and Principe", flag: "🇸🇹", dialCode: "+239", currency: "STN", symbol: "Db" },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦", dialCode: "+966", currency: "SAR", symbol: "ر.س" },
  { code: "SN", name: "Senegal", flag: "🇸🇳", dialCode: "+221", currency: "XOF", symbol: "Fr" },
  { code: "RS", name: "Serbia", flag: "🇷🇸", dialCode: "+381", currency: "RSD", symbol: "дин." },
  { code: "SC", name: "Seychelles", flag: "🇸🇨", dialCode: "+248", currency: "SCR", symbol: "₨" },
  { code: "SL", name: "Sierra Leone", flag: "🇸🇱", dialCode: "+232", currency: "SLL", symbol: "Le" },
  { code: "SG", name: "Singapore", flag: "🇸🇬", dialCode: "+65", currency: "SGD", symbol: "$" },
  { code: "SK", name: "Slovakia", flag: "🇸🇰", dialCode: "+421", currency: "EUR", symbol: "€" },
  { code: "SI", name: "Slovenia", flag: "🇸🇮", dialCode: "+386", currency: "EUR", symbol: "€" },
  { code: "SB", name: "Solomon Islands", flag: "🇸🇧", dialCode: "+677", currency: "SBD", symbol: "$" },
  { code: "SO", name: "Somalia", flag: "🇸🇴", dialCode: "+252", currency: "SOS", symbol: "Sh" },
  { code: "ES", name: "Spain", flag: "🇪🇸", dialCode: "+34", currency: "EUR", symbol: "€" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰", dialCode: "+94", currency: "LKR", symbol: "Rs" },
  { code: "SD", name: "Sudan", flag: "🇸🇩", dialCode: "+249", currency: "SDG", symbol: "ج.س." },
  { code: "SR", name: "Suriname", flag: "🇸🇷", dialCode: "+597", currency: "SRD", symbol: "$" },
  { code: "SZ", name: "Eswatini", flag: "🇸🇿", dialCode: "+268", currency: "SZL", symbol: "L" },
  { code: "SE", name: "Sweden", flag: "🇸🇪", dialCode: "+46", currency: "SEK", symbol: "kr" },
  { code: "CH", name: "Switzerland", flag: "🇨🇭", dialCode: "+41", currency: "CHF", symbol: "CHF" },
  { code: "SY", name: "Syria", flag: "🇸🇾", dialCode: "+963", currency: "SYP", symbol: "£" },
  { code: "TW", name: "Taiwan", flag: "🇹🇼", dialCode: "+886", currency: "TWD", symbol: "NT$" },
  { code: "TJ", name: "Tajikistan", flag: "🇹🇯", dialCode: "+992", currency: "TJS", symbol: "ЅМ" },
  { code: "TZ", name: "Tanzania", flag: "🇹🇿", dialCode: "+255", currency: "TZS", symbol: "TSh" },
  { code: "TH", name: "Thailand", flag: "🇹🇭", dialCode: "+66", currency: "THB", symbol: "฿" },
  { code: "TG", name: "Togo", flag: "🇹🇬", dialCode: "+228", currency: "XOF", symbol: "Fr" },
  { code: "TO", name: "Tonga", flag: "🇹🇴", dialCode: "+676", currency: "TOP", symbol: "T$" },
  { code: "TT", name: "Trinidad and Tobago", flag: "🇹🇹", dialCode: "+1-868", currency: "TTD", symbol: "$" },
  { code: "TN", name: "Tunisia", flag: "🇹🇳", dialCode: "+216", currency: "TND", symbol: "د.ت" },
  { code: "TR", name: "Turkey", flag: "🇹🇷", dialCode: "+90", currency: "TRY", symbol: "₺" },
  { code: "TM", name: "Turkmenistan", flag: "🇹🇲", dialCode: "+993", currency: "TMT", symbol: "m" },
  { code: "UG", name: "Uganda", flag: "🇺🇬", dialCode: "+256", currency: "UGX", symbol: "USh" },
  { code: "UA", name: "Ukraine", flag: "🇺🇦", dialCode: "+380", currency: "UAH", symbol: "₴" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾", dialCode: "+598", currency: "UYU", symbol: "$U" },
  { code: "UZ", name: "Uzbekistan", flag: "🇺🇿", dialCode: "+998", currency: "UZS", symbol: "so'm" },
  { code: "VU", name: "Vanuatu", flag: "🇻🇺", dialCode: "+678", currency: "VUV", symbol: "VT" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪", dialCode: "+58", currency: "VES", symbol: "Bs.S" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳", dialCode: "+84", currency: "VND", symbol: "₫" },
  { code: "YE", name: "Yemen", flag: "🇾🇪", dialCode: "+967", currency: "YER", symbol: "﷼" },
  { code: "ZM", name: "Zambia", flag: "🇿🇲", dialCode: "+260", currency: "ZMW", symbol: "ZK" },
  { code: "ZW", name: "Zimbabwe", flag: "🇿🇼", dialCode: "+263", currency: "ZWL", symbol: "$" }
];

export function parsePhoneNumber(phone: string) {
  if (!phone) return { countryCode: "", localNumber: "" };
  
  // Sort countries by dial code length in descending order to match longest prefix first (e.g. +1-268 before +1)
  const sortedCountries = [...ALL_COUNTRIES].sort((a, b) => b.dialCode.length - a.dialCode.length);
  
  for (const c of sortedCountries) {
    const dialCodeClean = c.dialCode.replace(/\s+/g, "").replace(/-/g, "");
    const normalizedPhone = phone.replace(/\s+/g, "").replace(/-/g, "");
    if (normalizedPhone.startsWith(dialCodeClean)) {
      return {
        countryCode: c.dialCode,
        localNumber: normalizedPhone.slice(dialCodeClean.length)
      };
    }
  }
  
  // Fallback if starts with + but no match found
  if (phone.startsWith("+")) {
    return { countryCode: "+1", localNumber: phone.slice(1) };
  }
  
  return { countryCode: "+1", localNumber: phone };
}
