const COUNTRY_CURRENCY_MAP: Record<string, string> = {
  AE: "AED", AF: "AFN", AL: "ALL", AM: "AMD", AO: "AOA",
  AR: "ARS", AU: "AUD", AW: "AWG", AZ: "AZN", BA: "BAM",
  BB: "BBD", BD: "BDT", BG: "BGN", BH: "BHD", BI: "BIF",
  BM: "BMD", BN: "BND", BO: "BOB", BR: "BRL", BS: "BSD",
  BT: "BTN", BW: "BWP", BY: "BYN", BZ: "BZD", CA: "CAD",
  CD: "CDF", CH: "CHF", CL: "CLP", CN: "CNY", CO: "COP",
  CR: "CRC", CU: "CUP", CV: "CVE", CZ: "CZK", DE: "EUR",
  DJ: "DJF", DK: "DKK", DO: "DOP", DZ: "DZD", EG: "EGP",
  ER: "ERN", ET: "ETB", FI: "EUR", FJ: "FJD", FK: "FKP",
  FR: "EUR", GB: "GBP", GE: "GEL", GH: "GHS", GI: "GIP",
  GM: "GMD", GN: "GNF", GR: "EUR", GT: "GTQ", GY: "GYD",
  HK: "HKD", HN: "HNL", HR: "EUR", HT: "HTG", HU: "HUF",
  ID: "IDR", IE: "EUR", IL: "ILS", IN: "INR", IQ: "IQD",
  IR: "IRR", IS: "ISK", IT: "EUR", JM: "JMD", JO: "JOD",
  JP: "JPY", KE: "KES", KG: "KGS", KH: "KHR", KM: "KMF",
  KP: "KPW", KR: "KRW", KW: "KWD", KY: "KYD", KZ: "KZT",
  LA: "LAK", LB: "LBP", LK: "LKR", LR: "LRD", LS: "LSL",
  LY: "LYD", MA: "MAD", MD: "MDL", MG: "MGA", MK: "MKD",
  ML: "XOF", MM: "MMK", MN: "MNT", MO: "MOP", MR: "MRU",
  MU: "MUR", MV: "MVR", MW: "MWK", MX: "MXN", MY: "MYR",
  MZ: "MZN", NA: "NAD", NE: "XOF", NG: "NGN", NI: "NIO",
  NL: "EUR", NO: "NOK", NP: "NPR", NZ: "NZD", OM: "OMR",
  PA: "PAB", PE: "PEN", PG: "PGK", PH: "PHP", PK: "PKR",
  PL: "PLN", PT: "EUR", PY: "PYG", QA: "QAR", RO: "RON",
  RS: "RSD", RU: "RUB", RW: "RWF", SA: "SAR", SB: "SBD",
  SC: "SCR", SD: "SDG", SE: "SEK", SG: "SGD", SH: "SHP",
  SL: "SLL", SN: "XOF", SO: "SOS", SR: "SRD", SS: "SSP",
  ST: "STN", SV: "USD", SY: "SYP", SZ: "SZL", TH: "THB",
  TJ: "TJS", TM: "TMT", TN: "TND", TO: "TOP", TR: "TRY",
  TT: "TTD", TW: "TWD", TZ: "TZS", UA: "UAH", UG: "UGX",
  US: "USD", UY: "UYU", UZ: "UZS", VE: "VES", VN: "VND",
  VU: "VUV", WS: "WST", YE: "YER", ZA: "ZAR", ZM: "ZMW",
  ZW: "ZWL",
};

export function getCurrencyForCountry(countryCode: string): string | null {
  if (!countryCode) return null;
  return COUNTRY_CURRENCY_MAP[countryCode.toUpperCase().trim()] ?? null;
}
