ALTER TABLE listing.bookings
ADD COLUMN IF NOT EXISTS service_fee DECIMAL(12,2) NOT NULL DEFAULT 0.00;

ALTER TABLE listing.bookings
ADD COLUMN IF NOT EXISTS tax_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00;

