#!/usr/bin/env sh

branch=$(git rev-parse --abbrev-ref HEAD)

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Current Branch: $branch"

if [ "$branch" = "main" ] || [ "$branch" = "dev" ]; then
  echo ""
  echo ""
  echo ""
  echo ""
  echo "WARNING: You are committing directly to '$branch'"
  echo "This isn't allowed"
  echo "Consider creating a feature branch instead and create Pull Request."
  echo "Do not force push or with verfy flag."
  echo ""
  echo ""
  echo ""
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  exit 1
else
  echo "Working on feature branch: $branch"
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

exit 0