name: Deploy to EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ZIKA__EC2_HOST }}
          username: ${{ secrets.ZIKA__USER }}
          key: ${{ secrets.ZIKA__SSH_KEY }}
          script: |
            cd ~/Zika-Booking
            git fetch origin dev
            git switch dev
            git reset --hard origin/dev

            pnpm install

            pnpm --filter auth-service db:generate && pnpm --filter auth-service db:migrate:deploy
            pnpm --filter listing-service db:generate && pnpm --filter listing-service db:migrate:deploy
            pnpm --filter payment-service db:generate && pnpm --filter payment-service db:migrate:deploy

            pnpm run build

            pm2 restart all
